payload:
  # 自定义直连
  - DOMAIN-SUFFIX,audiences.me
  - DOMAIN-SUFFIX,cinefiles.info
  - DOMAIN-SUFFIX,m-team.io
  - DOMAIN-SUFFIX,m-team.cc
  - DOMAIN-SUFFIX,caihc.site
  - DOMAIN-SUFFIX,caihc.top
  - DOMAIN-SUFFIX,test-ipv6.com
  - DOMAIN-SUFFIX,speedtest.net
  - DOMAIN-SUFFIX,276879.xyz
