payload:
  - '+.audiences.me'
  - '+.cinefiles.info'
  - '+.m-team.io'
  - '+.m-team.cc'
  - '+.caihc.site'
  - '+.test-ipv6.com'
  - '+.speedtest.net'
  - '+.08240315.xyz'
  - '+.zyhxjh.com'
  - '+.docip.net'
  - '+.ihuan.me'
  - '+.chcdev.top'
  - '+.276879.xyz'
  - '+.opencode.ai'
