payload:
  - '+.ai.google.dev'
  - '+.aistudio.google.com'
  - '+.bard.google.com'
  - '+.gemini.google.com'
  - '+.generativelanguage.googleapis.com'
  - '+.notebooklm.google'
  - '+.makersuite.google.com'
